---
swagger: '2.0'

info:
  version: "1.0.2"
  title: 'Demo'
  description: |
    ## A quick sample test
  
schemes:
 - http
 
paths:

  '/pets':
    
    post:
      description: | 
        ### Add a pet.
      
      consumes:
        - "application/vnd.api+json"
      produces:
        - "application/vnd.api+json"
          
      parameters:
      - name: "body"
        in: "body"
        description: "JSON representation of the new bill to be created"
        required: true
        schema: 
          $ref: "#/definitions/CreatePetDetail"

      responses:
        201:
          description: "Successfully created"
          schema:
            $ref: "#/definitions/PetDetailResponse"
          headers:
            Location:
              description: "URL pointing to newly added pet"
              type: string
        400:
          $ref: '#/responses/BadRequest'
        500:
          $ref: '#/responses/InternalError'
          
    get:
      description: | 
        ### Returns a list of pets.
        
      operationId: "listPets"
        
      consumes:
        - "application/vnd.api+json"
      produces:
        - "application/vnd.api+json"
          
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/PetListResponse"
        400:
          $ref: '#/responses/BadRequest'
        500:
          $ref: '#/responses/InternalError'
          
  
          
definitions:
  PetListResponse:
    type: object
    required: 
      - "data"
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/PetSummary"
      
          
  PetSummary:
    type: object
    required:
      - "name"
      - "type"
    properties:
      name:
        type: string
        example: "Kitten"
      type:
        type: string
        enum: 
          - "CAT"
          - "DOG"
          - "TORTOISE"
        example: "CAT"
  
  PetDetailResponse:
    type: object
    required:
      - "data"
    properties:
      data:
        type: object
        required:
         - "name"
         - "age"
         - "type"
        properties:
          name: 
            type: string
            example: "Kitten"
          age: 
            type: number
            example: "5"
          type:
            type: string
            enum: 
              - "CAT"
              - "DOG"
              - "TORTOISE"
            example: "TORTOISE"
            
  CreatePetDetail:
    type: object
    properties:
      name: 
        type: string
        example: "Kitten"
      age: 
        type: number
        example: "5"
      type: 
        type: string
        example: "CAT"
          

  ErrorResponse:
    type: object
    properties:
      errors:
        type: array
        items:
          type: object
          required:
            - "detail"
          properties:
            detail:
              type: string
              example: "type is missing"

parameters:
    
  petId:  
    name: "petId"
    description: "The unique identifier for the pet"
    in: "path"
    required: true
    type: string
    x-example: 111

responses:
  'BadRequest':
    description: "Input validation error"
    schema:
      $ref: '#/definitions/ErrorResponse'
  'InternalError':
    description: "Server error, no detail given"
  
          
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
# basePath: /edanielsen/Bills_Test/1.0.1
# Added by API Auto Mocking Plugin
basePath: /Pet/1.0.1