=begin
Demo

## A quick sample test 

OpenAPI spec version: 2.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end
class DefaultController < ApplicationController
  before_action :set_headers

  def set_headers
    response.headers['Content-Type'] = 'application/vnd.api+json'
  end

  def list_pets
    # Your code here

    pet1 = PetSummary.new.tap do |u|
      u.name = 'Awesome Cat - 1'
      u.type = 'CAT'
    end

    pet2 = PetSummary.new.tap do |u|
      u.name = 'Awesome Cat - 2'
      u.type = 'CAT'
    end

    render json: {data: [pet1, pet2]}
  end

  def pets_post
    # Your code here

    pet1 = PetDetailResponseData.new.tap do |u|
      u.name = 'Awesome Cat - 1'
      u.type = 'CAT'
      u.age = 2
    end

    pet2 = PetDetailResponseData.new.tap do |u|
      u.name = 'Awesome Cat - 2'
      u.type = 'CAT'
      u.age = 5
    end

    response.headers['location'] = 'http://localhost/dummy'
    render json: {data: [pet1, pet2]}, status: 201
  end
end
